<!DOCTYPE html>

<div class="container plus">
<h1>Liste des articles de la Catégorie : <?=$hereCat['c_title']?></h1>    
    
    <?php $i=0 ;?>
    <?php foreach($articles as $article):?>
    <article>
        <h2><?=$article['a_titre']?></h2>
        <p>Cet article a été réalisé par : <?=$article['u_prenom']?> <?=$article['u_nom']?> le <?=$article['a_date_publication']?></p>
        <img class="articleListe"src=<?= UPLOADS_URL.$article['a_image']?> alt=<?=$article['a_titre']?>>
        <div class='divOverflow'>
        <p><?=$article['a_contenu']?></p>
        </div>
        <div class='divBouton'><a href="articles.php?id=<?=$article['a_id']?>" class='boutonDetail'>Voir cet article</a></div>
    </article>
    <?php $i++?>
    <?php endforeach;?>

</div>