<!DOCTYPE html>

<div>
<h1>Liste des articles</h1>    
    
    <?$i=0?>
    <?php foreach($articles as $article):?>
    <article>
        <h2><?$article['a_titre']?></h2>
        <p>Cet article a été réalisé par : <?$article['a_auteur']?>  le <?$article['a_date_publication']?></p>
        <img src="<?= UPLOADS_URL.$article['a_image']?>" alt="<?=$article['a_titre']?>
        <p><?$article['a_contenu']?></p>
    </article>
    <?php $i++?>
    <?php endforeach;?>

</div>