<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">

     <!--responsive-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Accueil Blog</title>
    
    <link rel="stylesheet" href="../frontOffice/css/bootstrap.min.css" type="text/css" />
    
    <!--date-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
    
    <!--fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    
    
     <!--CSS-->
     <link rel="stylesheet" href="../frontOffice/css/normalize.css" type="text/css" />
     <link rel="stylesheet" href="../frontOffice/css/main.css" type="text/css" />
     <link href="https://fonts.googleapis.com/css?family=Dancing+Script" rel="stylesheet">

</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#" id="aMarque"><img src="../img/logo.png" alt="logo marque" id="logoMarque"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="index.php">Accueil <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <div class="dropdown">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Catégories
                        <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                            <?php foreach($categories as $categorie):?>
                            <li><a class="dropdown-item" href=categorie.php?id=<?= $categorie['c_id'] ?>><?= $categorie['c_title'] ?></a></li>
                            <?php endforeach;?>
                        <!--<li><a href="#" title="Lien 1">Lien 1</a></li>
                        <li><a href="#" title="Lien 2">Lien 2</a></li>
                        <li><a href="#" title="Lien 3">Lien 3</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#" title="Lien 4">Lien 4</a></li>-->
                        </ul>
                    </div>
                 <!-- </li>
                   <li class="nav-item">
                    <a class="nav-link" href="users.php">Mon profil</a>
                  </li>
                </ul>-->
                 <!-- <a class="btn btn-secondary btn-lg" href="logOut.php" role="button">Déconnexion <i class="fas fa-sign-out-alt"></i></a>-->
                
            </div>
        </nav>
        <div> <?php if(isset($flashbag) && $flashbag!=false):?>
        
            <?php foreach($flashbag as $message):?>
                <div class="alert alert-dismissible alert-<?=$message['level']?>" role="alert">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <p><?=$message['message']?></p>
                 </div>
            <?php endforeach;?>
       
        <?php endif;?>
        
        </div>
        
    </header>
    <main class="container-fluid">
      <section>
        <?php
          include('template/'.$vue);
        ?>
        
      </section>
    </main>
    <footer>
      <div>
          <a href="index.php"><img src="../img/kisspng-drawing-arrow-computer-icons-clip-art-hand-drawn-5abf6de9dd64c3.1439490315224949539068.png" > Retour à l'accueil</a>
      </div>
        
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 
    
</body>
