<form action="addCategorie.php" method="POST" enctype="multipart/form-data">
  <fieldset>
    <legend>Ajout d'une catégorie</legend>
    
    <div class="form-group">
      
      <label for="nomForm">Nom de la categorie</label>
      <input type="text" class="form-control" id="nomForm" aria-describedby="nom" name="nomForm" >
      
    </div>
    
      <button type="submit" class="btn btn-primary">Submit</button>
  </fieldset>
</form> 
  