<form action="addUser.php" method="POST" enctype="multipart/form-data">
  <fieldset>
    <legend>Création d'un utilisateur</legend>
    
    <div class="form-group">
      
      <label for="nomForm">Nom</label>
      <input type="text" class="form-control" id="nomForm" aria-describedby="nom" name="nomForm" placeholder="Votre nom">
      
    </div>
    
    <div class="form-group">
      
      <label for="prenomForm">Prénom</label>
      <input type="text" class="form-control" id="prenomForm" aria-describedby="prenom" name="prenomForm" placeholder="Votre prénom">
      
    </div>
    <div class="form-group">
      
      <label for="emailForm">E-mail</label>
      <input type="text" class="form-control" id="emailForm" aria-describedby="email" name="email" placeholder="Votre e-mail">
          
    </div>
    <div class="form-group">
      <label for="exampleInputPassword1">Password</label>
      <input type="password" class="form-control" id="exampleInputPassword1" name="password"placeholder="mot de passe">
    </div>
    
    
    <div class="form-group">
      <label for="statusForm">Status</label>
      <select class="form-control" id="statusForm" name ="statusForm" >
        <option  value="1">Valide</option>
        <option  value="0">Bloqué</option>
      </select>
    </div>
    
    <div class="form-group">
      <label for="roleForm">Rôle</label>
      <select class="form-control" id="roleForm" name="roleForm" >
        <option  value="ROLE_AUTEUR">Auteur</option>
        <option  value="ROLE_ADMIN">Administrateur</option>
      </select>
    </div>
    
 
  

    <button type="submit" class="btn btn-primary">Submit</button>
  </fieldset>
</form>