<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">

     <!--responsive-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Admin</title>
    
    <link rel="stylesheet" href="../backOffice/css/bootstrap.min.css" type="text/css" />
    
    <!--date-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/css/tempusdominus-bootstrap-4.min.css" />
    
    <!--fontawesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    
    <!--tinyMCE pour permetre ecriture stylisée-->
    <script src="https://cloud.tinymce.com/5/tinymce.min.js"></script>
    <script>tinymce.init({ selector:'textarea' });</script>
     <!--CSS-->
     <link rel="stylesheet" href="../backOffice/css/normalize.css" type="text/css" />
     <link rel="stylesheet" href="../backOffice/css/main.css" type="text/css" />
     
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <a class="navbar-brand" href="#">BackOffice de <?=$_SESSION['user']['prenom']?></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="index.php">Accueil <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="article.php">Article</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="categorie.php">Catégorie</a>
                  </li>
                  <!--<li class="nav-item">
                    <a class="nav-link" href="ModerationCommentaire.php">Commentaires</a>
                  </li>-->
                   <li class="nav-item">
                    <a class="nav-link" href="users.php">Utilisateur</a>
                  </li>
                </ul>
                  <a class="btn btn-secondary btn-lg" href="logOut.php" role="button">Déconnexion <i class="fas fa-sign-out-alt"></i></a>
                
            </div>
        </nav>
    </header>
    <main class="container-fluid">
      <section>
        <?php
          include('template/'.$vue);
        ?>
      </section>
    </main>
    <footer>
    </footer>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script> 
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
 
    
</body>
